[logger]
filter = "info"
color = true
log_to_file = true
log_to_stdout = true

[sentry]
# set to blank to disable sentry error collection
dsn = "https://48c6a88d92e246478e2d53b5917a887c@sentry.io/1422795"
# if you are willing to help us to improve,
# please leave a way to contact you when we have troubles to reproduce the errors.
# org_contact = ""

[miner]
rpc_url = "http://127.0.0.1:8114/"
block_on_submit = true
# block template polling interval in milliseconds
poll_interval = 1000

[gpus]
# the gpu you want to use, can be 0,1,2,3,..
gpuids     = [0]

# cpu miner, the architecture you want to use, 0 is avx2, 1 is avx512
# avx2 miner can run on most intel CPUs, but slower than avx512
[[cpus]]
arch = 0
threads = 2

[[cpus]]
arch = 1
threads = 2